CREATE TABLE 
    AUTOS 
    (
        AUTO_ID SERIAL NOT NULL,
        TIPO_ID INT4 NULL,
        MARCA_ID INT4 NULL,
        PLACA  VARCHAR(10) NOT NULL,
        COLOR  VARCHAR(50) NOT NULL,
        CHASIS VARCHAR(255) NOT NULL,
        CONSTRAINT PK_AUTOS PRIMARY KEY (AUTO_ID)
    );
COMMENT ON TABLE AUTOS IS
'AUTOS';
COMMENT ON COLUMN AUTOS.AUTO_ID IS
'AUTO_ID';
COMMENT ON COLUMN AUTOS.TIPO_ID IS
'TIPO_ID';
COMMENT ON COLUMN AUTOS.MARCA_ID IS
'MARCA_ID';
COMMENT ON COLUMN AUTOS.PLACA IS
'PLACA';
COMMENT ON COLUMN AUTOS.COLOR IS
'COLOR';
COMMENT ON COLUMN AUTOS.CHASIS IS
'CHASIS';
CREATE TABLE 
    MARCAS 
    (
        MARCA_ID SERIAL NOT NULL,
        NOMBRE VARCHAR(255) NOT NULL,
        ESTADO BOOL NOT NULL,
        CONSTRAINT PK_MARCAS PRIMARY KEY (MARCA_ID)
    );
COMMENT ON TABLE MARCAS IS
'MARCAS';
COMMENT ON COLUMN MARCAS.MARCA_ID IS
'MARCA_ID';
COMMENT ON COLUMN MARCAS.NOMBRE IS
'NOMBRE';
COMMENT ON COLUMN MARCAS.ESTADO IS
'ESTADO';
CREATE TABLE 
    MODELOS 
    (
        MODELO_ID SERIAL NOT NULL,
        MARCA_ID INT4 NULL,
        NOMBRE VARCHAR(255) NOT NULL,
        ESTADO BOOL NOT NULL,
        CONSTRAINT PK_MODELOS PRIMARY KEY (MODELO_ID)
    );
COMMENT ON TABLE MODELOS IS
'MODELOS';
COMMENT ON COLUMN MODELOS.MODELO_ID IS
'MODELO_ID';
COMMENT ON COLUMN MODELOS.MARCA_ID IS
'MARCA_ID';
COMMENT ON COLUMN MODELOS.NOMBRE IS
'NOMBRE';
COMMENT ON COLUMN MODELOS.ESTADO IS
'ESTADO';
CREATE TABLE 
    MOVILIZACIONES 
    (
        MOVILIZACION_ID SERIAL NOT NULL,
        AUTO_ID INT4 NULL,
        FECHA DATE NOT NULL,
        ESTADO BOOL NOT NULL,
        CONSTRAINT PK_MOVILIZACIONES PRIMARY KEY (MOVILIZACION_ID)
    );
COMMENT ON TABLE MOVILIZACIONES IS
'MOVILIZACIONES';
COMMENT ON COLUMN MOVILIZACIONES.MOVILIZACION_ID IS
'movilizacion_id';
COMMENT ON COLUMN MOVILIZACIONES.AUTO_ID IS
'AUTO_ID';
COMMENT ON COLUMN MOVILIZACIONES.FECHA IS
'fecha';
COMMENT ON COLUMN MOVILIZACIONES.ESTADO IS
'estado';
CREATE TABLE 
    ROLES 
    (
        ROL_ID SERIAL NOT NULL,
        ESTADO BOOLEAN NOT NULL,
        NOMBRE CHARACTER VARYING(20) NOT NULL,
        CONSTRAINT ROLES_PK PRIMARY KEY (ROL_ID)
    );
COMMENT ON TABLE ROLES IS
'ROLES';
COMMENT ON COLUMN ROLES.ROL_ID IS
'ROL_ID';
COMMENT ON COLUMN ROLES.ESTADO IS
'ESTADO';
COMMENT ON COLUMN ROLES.NOMBRE IS
'NOMBRE';
CREATE TABLE 
    ROLES_USUARIOS 
    (
        ROL_USUARIO_ID SERIAL NOT NULL,
        ESTADO BOOLEAN NOT NULL,
        ROL_ID INT4 NOT NULL,
        USUARIO_ID INT4 NOT NULL,
        CONSTRAINT ROLES_USUARIOS_PK PRIMARY KEY (ROL_USUARIO_ID)
    );
COMMENT ON TABLE ROLES_USUARIOS IS
'ROLES_USUARIOS';
COMMENT ON COLUMN ROLES_USUARIOS.ROL_USUARIO_ID IS
'ROL_USUARIO_ID';
COMMENT ON COLUMN ROLES_USUARIOS.ESTADO IS
'ESTADO';
COMMENT ON COLUMN ROLES_USUARIOS.ROL_ID IS
'ROL_ID';
COMMENT ON COLUMN ROLES_USUARIOS.USUARIO_ID IS
'USUARIO_ID';
CREATE TABLE 
    TIPOS 
    (
        TIPO_ID SERIAL NOT NULL,
        NOMBRE VARCHAR(255) NOT NULL,
        ESTADO BOOL NULL,
        CONSTRAINT PK_TIPOS PRIMARY KEY (TIPO_ID)
    );
COMMENT ON TABLE TIPOS IS
'TIPOS';
COMMENT ON COLUMN TIPOS.TIPO_ID IS
'TIPO_ID';
COMMENT ON COLUMN TIPOS.NOMBRE IS
'NOMBRE';
COMMENT ON COLUMN TIPOS.ESTADO IS
'ESTADO';
CREATE TABLE 
    USUARIOS 
    (
        USUARIO_ID SERIAL NOT NULL,
        ENABLED  BOOLEAN NOT NULL,
        PASSWORD CHARACTER VARYING(60) NOT NULL,
        USERNAME CHARACTER VARYING(20) NOT NULL,
        CONSTRAINT USUARIOS_PK PRIMARY KEY (USUARIO_ID)
    );
COMMENT ON TABLE USUARIOS IS
'USUARIOS';
COMMENT ON COLUMN USUARIOS.USUARIO_ID IS
'USUARIO_ID';
COMMENT ON COLUMN USUARIOS.ENABLED IS
'ENABLED';
COMMENT ON COLUMN USUARIOS.PASSWORD IS
'PASSWORD';
COMMENT ON COLUMN USUARIOS.USERNAME IS
'USERNAME';
ALTER TABLE 
    AUTOS ADD CONSTRAINT FK_AUTOS_REFERENCE_MARCAS FOREIGN KEY (MARCA_ID) REFERENCES MARCAS 
    (MARCA_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;
ALTER TABLE 
    AUTOS ADD CONSTRAINT FK_AUTOS_REFERENCE_TIPOS FOREIGN KEY (TIPO_ID) REFERENCES TIPOS (TIPO_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;
ALTER TABLE 
    MODELOS ADD CONSTRAINT FK_MODELOS_REFERENCE_MARCAS FOREIGN KEY (MARCA_ID) REFERENCES MARCAS 
    (MARCA_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;
ALTER TABLE 
    MOVILIZACIONES ADD CONSTRAINT FK_MOVILIZA_REFERENCE_AUTOS FOREIGN KEY (AUTO_ID) REFERENCES 
    AUTOS (AUTO_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;
ALTER TABLE 
    ROLES_USUARIOS ADD CONSTRAINT FK_ROLES FOREIGN KEY (ROL_ID) REFERENCES ROLES (ROL_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;
ALTER TABLE 
    ROLES_USUARIOS ADD CONSTRAINT FK_USUARIOS FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS 
    (USUARIO_ID)
ON 
DELETE 
    RESTRICT 
ON 
UPDATE 
    RESTRICT;

